/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: hoschu (https://sketchfab.com/hoschu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/door-adf292f437f24151918a3b16ecef52d2
Title: Door
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export default function Door(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('assets/objects/door/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={(nodes.Door_Default_0 as THREE.Mesh).geometry} scale={[.1,.005,1]} material={materials.Default} />
    </group>
  )
}


