/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: adventurer (https://sketchfab.com/ahmagh2e)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/window-e7a957f3585a4ced8aeb23e9525f0b87
Title: Window
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as  THREE from 'three';

export function Window(props : JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('assets/objects/window/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={[0.0042, 0.0044,0.01]}>
        <group position={[0, 74, 0]}>
          <mesh geometry={(nodes.UP_w_0 as THREE.Mesh).geometry} material={materials.material} />
          <mesh geometry={(nodes.UP_g_0 as THREE.Mesh).geometry} material={materials.material_1} />
        </group>
        <group position={[54.292, 0, 5.722]}>
          <mesh geometry={(nodes.L_w_0 as THREE.Mesh).geometry} material={materials.material} />
          <mesh geometry={(nodes.L_g_0 as THREE.Mesh).geometry} material={materials.material_1} />
        </group>
        <group position={[-54.292, 0, -1.164]}>
          <mesh geometry={(nodes.R_w_0 as THREE.Mesh).geometry} material={materials.material} />
          <mesh geometry={(nodes.R_g_0 as THREE.Mesh).geometry} material={materials.material_1} />
        </group>
        <mesh geometry={(nodes.F_w_0 as THREE.Mesh).geometry} material={materials.material} position={[0, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
